/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package dev.castocolina.gradle.plugin

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'json2yaml' plugin.
 */
public class Json2YamlPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("json2yaml")

        then:
        project.tasks.findByName("transformYaml") != null
        // project.tasks.findByName("").

    }
}
